// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

import apiSidebar from './docs/petstore/sidebar.js';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  myApiSidebar: apiSidebar,
};

export default sidebars;
